name: Deploy ASP.NET Core API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via Git Pull
        run: |
          ssh -i ~/.ssh/ec2.pem \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          cd /home/ubuntu/Jwt_project

          git pull origin main

          dotnet restore
          dotnet publish -c Release -o /var/www/userauthapi

          sudo systemctl restart userauthapi

          EOF

