name: Deploy ASP.NET Core API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore UserAuthApi.csproj

      - name: Publish
        run: dotnet publish UserAuthApi.csproj -c Release -o publish

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Create deploy folder
        run: |
          ssh -i ~/.ssh/ec2.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "sudo mkdir -p /var/www/userauthapi && sudo chown -R ubuntu:ubuntu /var/www/userauthapi"

      - name: Upload files
        run: |
          rsync -avz \
          -e "ssh -i ~/.ssh/ec2.pem" \
          publish/ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/userauthapi/

      - name: Restart Service
        run: |
          ssh -i ~/.ssh/ec2.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "sudo systemctl restart userauthapi"
          